//! Generated frontend contract: TypeScript types, canonical section order,
//! default recipe fixture, parameter ranges, and the shared Lap legacy
//! saturation conversion. The generated module is committed under `gen/` and
//! byte-compared against this generator by tests so it can never drift
//! silently from the Rust model.

use crate::descriptors::PARAM_DESCRIPTORS;
use crate::types::{Recipe, RecipeEnvelope};
use serde_json::{Value, json};

pub const GENERATED_TS_PATH: &str = "gen/recipe.ts";
pub const GENERATED_JSON_PATH: &str = "gen/default-recipe.json";

fn ts_header() -> String {
    format!(
        "// Generated by rapidraw-edit-model v{} (src/contract.rs). DO NOT EDIT.\n\
         // Regenerate with:\n\
         //   cargo test --manifest-path crates/rapidraw-edit-model/Cargo.toml -- --ignored update_generated_files\n\
         // then commit the changed files under crates/rapidraw-edit-model/gen/.\n\
         // Schema documentation: Lap repository docs/raw-development/schema.md.\n\n",
        crate::MODEL_VERSION
    )
}

/// The default recipe serialized as canonical (compact, key-sorted) JSON.
pub fn default_recipe_json() -> String {
    serde_json::to_string(&Recipe::default()).expect("default recipe serializes")
}

/// Serialize an envelope as canonical JSON (used for fixtures).
pub fn generate_envelope_fixture_json(envelope: &RecipeEnvelope) -> String {
    serde_json::to_string(envelope).expect("envelope serializes")
}

fn param_ranges_json() -> String {
    let mut map = serde_json::Map::new();
    for d in PARAM_DESCRIPTORS {
        map.insert(
            d.key.to_string(),
            json!({
                "min": d.min,
                "max": d.max,
                "step": d.step,
                "section": d.section.map(|s| s.as_str()),
            }),
        );
    }
    serde_json::to_string_pretty(&Value::Object(map)).expect("ranges serialize")
}

const INTERFACES: &str = r#"export type SectionId = 'basic' | 'curves' | 'color' | 'details' | 'effects';

export const CANONICAL_SECTION_ORDER: SectionId[] = ['basic', 'curves', 'color', 'details', 'effects'];

export type ToneMapper = 'basic' | 'agx';
export type CurveMode = 'point' | 'parametric';
export type LensCorrectionMode = 'auto' | 'manual';
export type LensBlurShape = 'circle' | 'hexagon' | 'octagon' | 'ring';
export type SubMaskMode = 'additive' | 'subtractive' | 'intersect';

export interface LevelsChannel { inputBlack: number; inputWhite: number; outputBlack: number; outputWhite: number; midtone: number; }
export interface Levels { enabled: boolean; rgb: LevelsChannel; red: LevelsChannel; green: LevelsChannel; blue: LevelsChannel; }
export interface CurvePoint { x: number; y: number; }
export interface Curves { [channel: string]: CurvePoint[]; luma: CurvePoint[]; red: CurvePoint[]; green: CurvePoint[]; blue: CurvePoint[]; }
export interface ParametricCurveSettings { darks: number; shadows: number; highlights: number; lights: number; whiteLevel: number; blackLevel: number; split1: number; split2: number; split3: number; }
export interface ParametricCurve { [channel: string]: ParametricCurveSettings; luma: ParametricCurveSettings; red: ParametricCurveSettings; green: ParametricCurveSettings; blue: ParametricCurveSettings; }
export interface HueSatLum { hue: number; saturation: number; luminance: number; }
export interface Hsl { [channel: string]: HueSatLum; reds: HueSatLum; oranges: HueSatLum; yellows: HueSatLum; greens: HueSatLum; aquas: HueSatLum; blues: HueSatLum; purples: HueSatLum; magentas: HueSatLum; }
export interface ColorGrading { [zone: string]: number | HueSatLum; balance: number; blending: number; global: HueSatLum; shadows: HueSatLum; midtones: HueSatLum; highlights: HueSatLum; }
export interface ColorCalibration { shadowsTint: number; redHue: number; redSaturation: number; greenHue: number; greenSaturation: number; blueHue: number; blueSaturation: number; }
export interface CropRect { x: number; y: number; width: number; height: number; }
export interface LensDistortionParams { k1: number; k2: number; k3: number; model: number; tca_vr: number; tca_vb: number; vig_k1: number; vig_k2: number; vig_k3: number; }
/** Provenance of the lens profile the persisted lensDistortionParams were resolved from. */
export interface LensProfileRef { uri: string; maker: string; model: string; version: string; sha256: string; }
export interface SectionVisibility { [section: string]: boolean; basic: boolean; curves: boolean; color: boolean; details: boolean; effects: boolean; }
export interface MaskSectionVisibility { [section: string]: boolean; basic: boolean; curves: boolean; color: boolean; details: boolean; effects: boolean; }
/**
 * Typed geometry for the supported non-AI mask kinds. Positions are
 * normalized fractions of the oriented full-frame size; lengths (brush
 * diameter, radii, gradient range) are normalized fractions of the oriented
 * frame width; rotation is degrees in [0, 360); feather is [0, 1]; flow is
 * [0, 100]. Unsupported kinds (AI, luminance/color) have no typed geometry.
 */
export interface MaskPoint { x: number; y: number; }
export type BrushTool = 'brush' | 'eraser';
export interface BrushLine { tool: BrushTool; brushSize: number; feather: number; points: MaskPoint[]; }
export interface FlowLine { tool: BrushTool; brushSize: number; feather: number; flow: number; points: MaskPoint[]; }
export type MaskGeometry =
  | { type: 'brush'; lines: BrushLine[] }
  | { type: 'flow'; lines: FlowLine[] }
  | { type: 'linear'; startX: number; startY: number; endX: number; endY: number; range: number }
  | { type: 'radial'; centerX: number; centerY: number; radiusX: number; radiusY: number; rotation: number; feather: number }
  | { type: 'all' };
export interface SubMask { id: string; name: string | null; invert: boolean; visible: boolean; opacity: number; mode: SubMaskMode; type: string; parameters: unknown; geometry: MaskGeometry | null; }
export interface MaskLocalAdjustments {
  exposure: number; brightness: number; contrast: number; highlights: number; shadows: number; whites: number; blacks: number;
  toneMapper: ToneMapper;
  temperature: number; tint: number; vibrance: number; saturation: number; hue: number;
  colorGrading: ColorGrading; hsl: Hsl; colorCalibration: ColorCalibration;
  clarity: number; structure: number; dehaze: number; "centré": number;
  sharpness: number; sharpnessThreshold: number; lumaNoiseReduction: number; colorNoiseReduction: number;
  chromaticAberrationRedCyan: number; chromaticAberrationBlueYellow: number;
  glowAmount: number; halationAmount: number; flareAmount: number;
  curves: Curves; pointCurves: Curves; parametricCurve: ParametricCurve; curveMode: CurveMode;
  sectionVisibility: MaskSectionVisibility;
}
export interface MaskContainer {
  id: string; name: string; invert: boolean; visible: boolean; opacity: number;
  adjustments: MaskLocalAdjustments; subMasks: SubMask[];
  unsupported: Record<string, unknown>;
}
"#;

const RECIPE_INTERFACE: &str = r#"/**
 * The semantic development recipe: persisted render data only.
 *
 * UI-only state (clipping overlay, AI patch session state, accordion
 * expansion, zoom, selected tool, hover previews) is intentionally absent.
 * Geometry uses the oriented, normalized coordinate system: origin at the
 * top-left of the image after orientationSteps clockwise quarter turns, unit
 * axes, crop components in [0, 1] with x + width <= 1 and y + height <= 1.
 */
export interface Recipe {
  exposure: number; brightness: number; contrast: number; highlights: number; shadows: number; whites: number; blacks: number;
  toneMapper: ToneMapper;
  levels: Levels;
  curves: Curves; pointCurves: Curves; parametricCurve: ParametricCurve; curveMode: CurveMode;
  temperature: number; tint: number; vibrance: number; saturation: number; hue: number;
  colorGrading: ColorGrading; hsl: Hsl; colorCalibration: ColorCalibration;
  clarity: number; structure: number; dehaze: number; "centré": number;
  sharpness: number; sharpnessThreshold: number; lumaNoiseReduction: number; colorNoiseReduction: number;
  chromaticAberrationRedCyan: number; chromaticAberrationBlueYellow: number;
  glowAmount: number; halationAmount: number; flareAmount: number;
  grainAmount: number; grainSize: number; grainRoughness: number;
  vignetteAmount: number; vignetteMidpoint: number; vignetteRoundness: number; vignetteFeather: number;
  lutIntensity: number; lutIsSceneReferred: boolean; lutName: string | null; lutPath: string | null; lutSize: number;
  lensBlurEnabled: boolean; lensBlurAmount: number; lensBlurDiffusion: number; lensBlurShape: LensBlurShape;
  lensBlurDepthMap: string | null;
  lensBlurMinDepth: number; lensBlurMaxDepth: number; lensBlurMinFade: number; lensBlurMaxFade: number;
  rotation: number; orientationSteps: number; flipHorizontal: boolean; flipVertical: boolean;
  crop: CropRect | null; aspectRatio: number | null;
  transformDistortion: number; transformVertical: number; transformHorizontal: number; transformRotate: number;
  transformAspect: number; transformScale: number; transformXOffset: number; transformYOffset: number;
  lensCorrectionMode: LensCorrectionMode; lensMaker: string | null; lensModel: string | null;
  lensDistortionAmount: number; lensVignetteAmount: number; lensTcaAmount: number;
  lensDistortionEnabled: boolean; lensTcaEnabled: boolean; lensVignetteEnabled: boolean;
  lensDistortionParams: LensDistortionParams | null;
  lensProfile: LensProfileRef | null;
  masks: MaskContainer[];
  sectionVisibility: SectionVisibility;
  sectionOrder: SectionId[];
}
"#;

const SATURATION_HELPERS: &str = r#"/**
 * Lap legacy CSS-filter scale: 0..=200 with neutral 100.
 * Recipe deviation scale: -100..=100 with neutral 0 (RapidRAW semantics).
 * The conversion is arithmetic; field names are never matched by similarity.
 */
function clamp(value: number, min: number, max: number): number {
  if (Number.isNaN(value)) return min;
  return Math.min(max, Math.max(min, value));
}

export function saturationFromLapLegacy(legacy: number): number {
  return clamp(legacy, 0, 200) - 100;
}

export function saturationToLapLegacy(recipe: number): number {
  return clamp(recipe, -100, 100) + 100;
}
"#;

/// Generate the complete TypeScript contract module.
pub fn generate_typescript() -> String {
    let mut out = String::new();
    out.push_str(&ts_header());
    out.push_str("export const RECIPE_SCHEMA_VERSION = 1;\n\n");
    out.push_str(INTERFACES);
    out.push('\n');
    out.push_str(RECIPE_INTERFACE);
    out.push('\n');
    out.push_str("export const DEFAULT_RECIPE: Recipe = ");
    out.push_str(
        &serde_json::to_string_pretty(&Recipe::default()).expect("default recipe serializes"),
    );
    out.push_str(";\n\n");
    out.push_str("export interface ParamRange { min: number; max: number; step: number; section: SectionId | null; }\n");
    out.push_str("export const RECIPE_PARAM_RANGES: Record<string, ParamRange> = ");
    out.push_str(&param_ranges_json());
    out.push_str(";\n\n");
    out.push_str(SATURATION_HELPERS);
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use std::path::Path;

    /// Regenerate the committed contract files. Run explicitly:
    /// `cargo test --manifest-path crates/rapidraw-edit-model/Cargo.toml -- --ignored update_generated_files`
    #[test]
    #[ignore = "writes generated files; run explicitly after contract changes"]
    fn update_generated_files() {
        let gen_dir = Path::new(env!("CARGO_MANIFEST_DIR")).join("gen");
        fs::create_dir_all(&gen_dir).unwrap();
        fs::write(gen_dir.join("recipe.ts"), generate_typescript()).unwrap();
        fs::write(gen_dir.join("default-recipe.json"), default_recipe_json()).unwrap();
    }
}
