import { describe, expect, it } from 'vitest';
// Generated by rapidraw-edit-model; the frontend consumes the same contract
// as the Rust engine.
import {
  CANONICAL_SECTION_ORDER,
  DEFAULT_RECIPE,
  RECIPE_SCHEMA_VERSION,
  saturationFromLapLegacy,
  saturationToLapLegacy,
} from '../../crates/rapidraw-edit-model/gen/recipe';
import { INITIAL_ADJUSTMENTS, adjustmentsToRecipe, recipeToAdjustments } from '../utils/adjustments';

describe('generated recipe contract', () => {
  it('exposes the current schema version and canonical section order', () => {
    expect(RECIPE_SCHEMA_VERSION).toBe(1);
    expect(CANONICAL_SECTION_ORDER).toEqual(['basic', 'curves', 'color', 'details', 'effects']);
  });

  it('keeps UI-only fields outside the recipe contract', () => {
    expect('showClipping' in DEFAULT_RECIPE).toBe(false);
    expect('aiPatches' in DEFAULT_RECIPE).toBe(false);
  });

  it('derives INITIAL_ADJUSTMENTS from the generated default recipe', () => {
    expect(INITIAL_ADJUSTMENTS.saturation).toBe(DEFAULT_RECIPE.saturation);
    expect(INITIAL_ADJUSTMENTS.saturation).toBe(0);
    expect(INITIAL_ADJUSTMENTS.grainSize).toBe(DEFAULT_RECIPE.grainSize);
    expect(INITIAL_ADJUSTMENTS.grainSize).toBe(25);
    expect(INITIAL_ADJUSTMENTS.grainRoughness).toBe(50);
    expect(INITIAL_ADJUSTMENTS.sharpnessThreshold).toBe(15);
    expect(INITIAL_ADJUSTMENTS.lutIntensity).toBe(100);
    expect(INITIAL_ADJUSTMENTS.transformScale).toBe(100);
    expect(INITIAL_ADJUSTMENTS.lensBlurAmount).toBe(40);
    expect(INITIAL_ADJUSTMENTS.colorGrading.blending).toBe(50);
    expect(INITIAL_ADJUSTMENTS.parametricCurve?.luma.split1).toBe(25);
    expect(INITIAL_ADJUSTMENTS.sectionVisibility).toEqual(DEFAULT_RECIPE.sectionVisibility);
    expect(INITIAL_ADJUSTMENTS.showClipping).toBe(false);
    expect(INITIAL_ADJUSTMENTS.aiPatches).toEqual([]);
  });

  it('converts Lap legacy saturation arithmetically, not by name mapping', () => {
    expect(saturationFromLapLegacy(100)).toBe(0);
    expect(saturationFromLapLegacy(0)).toBe(-100);
    expect(saturationFromLapLegacy(200)).toBe(100);
    expect(saturationToLapLegacy(0)).toBe(100);
    expect(saturationFromLapLegacy(saturationToLapLegacy(-42.5))).toBe(-42.5);
  });

  it('round-trips the default recipe through the host adapters', () => {
    const recipe = adjustmentsToRecipe(INITIAL_ADJUSTMENTS);
    expect(recipe).toEqual(DEFAULT_RECIPE);
    const back = recipeToAdjustments(DEFAULT_RECIPE);
    expect(back.saturation).toBe(0);
    expect(back.showClipping).toBe(false);
    expect(back.aiPatches).toEqual([]);
    expect(back.lutData).toBeNull();
    expect(back.crop).toBeNull();
  });

  it('requires oriented dimensions to materialize a recipe crop', () => {
    const cropped = {
      ...DEFAULT_RECIPE,
      crop: { x: 0.1, y: 0.1, width: 0.5, height: 0.5 },
    };
    expect(() => recipeToAdjustments(cropped)).toThrow();
    const legacy = recipeToAdjustments(cropped, { width: 1000, height: 500 });
    expect(legacy.crop).toEqual({ unit: 'px', x: 100, y: 50, width: 500, height: 250 });
  });
});
